# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu-120/xsub/val_data_joint.npy
  label_path: ./data/ntu-120/xsub/val_label.pkl
  duo_only: True
  debug: False

# model
model: model.dragcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 10
weights: ./runs/ntu-120_cs_dragcn_joint-49-65350.pt

work_dir: ./work_dir/ntu-120/xsub/dragcn_test_joint
model_saved_name: ./runs/ntu-120_cs_dragcn_test_joint
save_score: True
