# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_bone.npy
  label_path: ./data/ntu/xview/val_label.pkl
  duo_only: True
  debug: False

# model
model: model.dragcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: 0
test_batch_size: 10
weights: ./runs/ntu_cv_dragcn_bone-47-33024.pt

work_dir: ./work_dir/ntu/xview/dragcn_test_bone
model_saved_name: ./runs/ntu_cv_dragcn_test_bone
save_score: True
