work_dir: ./work_dir/ntu-120/xset/agcn_joint
model_saved_name: ./runs/ntu-120_cv_agcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu-120/xset/train_data_joint.npy
  label_path: ./data/ntu-120/xset/train_label.pkl
  duo_only: True
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu-120/xset/val_data_joint.npy
  label_path: ./data/ntu-120/xset/val_label.pkl
  duo_only: True
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 26
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: 0
batch_size: 16
test_batch_size: 10
num_epoch: 50
nesterov: True
save_interval: 5
eval_interval: 5
