work_dir: ./work_dir/ntu/xsub/agcn_bone
model_saved_name: ./runs/ntu_cs_agcn_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xsub/train_data_bone.npy
  label_path: ./data/ntu/xsub/train_label.pkl
  duo_only: True
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_bone.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  duo_only: True
  debug: False

# model
model: model.dragcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [30, 40]

# training
device: 0
batch_size: 10
test_batch_size: 10
num_epoch: 50
nesterov: True
