# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/val_data_bone.npy
  label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
  duo_only: True
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 16
weights: ./runs/ntu_cs_agcn_bone-41-30702.pt

work_dir: ./work_dir/ntu/xsub/agcn_test_bone
model_saved_name: ./runs/ntu_cs_agcn_test_bone
save_score: True
